const express=require("express"),path=require("path"),helmet=require("helmet"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),DB=require("better-sqlite3");
const app=express(),db=new DB("enekocoin.db"),SECRET=process.env.JWT_SECRET||"CHANGE_ME",PORT=process.env.PORT||3000;
app.use(helmet({contentSecurityPolicy:false}));app.use(cors());app.use(express.json());app.use(express.static("public"));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,password TEXT,name TEXT);
CREATE TABLE IF NOT EXISTS balances(id INTEGER PRIMARY KEY,user_id INTEGER,asset TEXT,balance REAL,UNIQUE(user_id,asset));
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY,user_id INTEGER,type TEXT,asset TEXT,amount REAL,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,user_id INTEGER,action TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const sign=u=>jwt.sign({id:u.id,email:u.email},SECRET,{expiresIn:"2h"});
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch(e){res.status(401).json({error:"Unauthorized"})}}
app.post("/api/register",async(req,res)=>{let{email,password,name}=req.body;if(!email||!password||password.length<8)return res.status(400).json({error:"Email and password of 8+ characters required"});try{let h=await bcrypt.hash(password,12),r=db.prepare("INSERT INTO users(email,password,name) VALUES(?,?,?)").run(email.toLowerCase(),h,name||"");for(let a of ["BTC","ETH","USDT","ENK"])db.prepare("INSERT INTO balances(user_id,asset,balance) VALUES(?,?,0)").run(r.lastInsertRowid,a);res.json({token:sign({id:r.lastInsertRowid,email}),user:{email}})}catch(e){res.status(409).json({error:"Account already exists"})}});
app.post("/api/login",async(req,res)=>{let u=db.prepare("SELECT * FROM users WHERE email=?").get((req.body.email||"").toLowerCase());if(!u||!(await bcrypt.compare(req.body.password||"",u.password)))return res.status(401).json({error:"Invalid credentials"});res.json({token:sign(u),user:{id:u.id,email:u.email,name:u.name}})});
app.get("/api/me",auth,(req,res)=>{let u=db.prepare("SELECT id,email,name FROM users WHERE id=?").get(req.user.id),balances=db.prepare("SELECT asset,balance FROM balances WHERE user_id=?").all(req.user.id);res.json({user:u,balances})});
app.get("/api/markets",(req,res)=>res.json([{asset:"BTC",price:68420,change:2.41},{asset:"ETH",price:3245,change:1.84},{asset:"USDT",price:1,change:.02},{asset:"ENK",price:.84,change:5.17}]));
app.get("/api/transactions",auth,(req,res)=>res.json(db.prepare("SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC").all(req.user.id)));
app.post("/api/paper-order",auth,(req,res)=>{if(process.env.DEMO_MODE!=="true")return res.status(403).json({error:"Demo mode is disabled"});let{side,asset,amount}=req.body;if(!["buy","sell"].includes(side)||!["BTC","ETH","USDT","ENK"].includes(asset)||!(Number(amount)>0))return res.status(400).json({error:"Invalid order"});db.prepare("INSERT INTO transactions(user_id,type,asset,amount,status) VALUES(?,?,?,?,?)").run(req.user.id,side.toUpperCase(),asset,Number(amount),"PAPER");res.json({message:"Paper order recorded; no real asset moved."})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public/index.html")));app.listen(PORT,()=>console.log("EnekoCoin: http://localhost:"+PORT));